### PR TITLE
Clarify menu buttons in KK standalone

### PR DESCRIPTION
**Pull request by ScottChesworth**

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Might be worth doing this with the Kontakt buttons too, in particular it's probably worth clarifying that the Shop button will open in the default web browser. The Kontakt overlay isn't working here yet so I didn't mess with it.

**Comment by Timtam** [comment]
Looks good and works too, why doesn't Kontakt work for you? Did you try standalone and plugin? Don't forget that you need to run ReaHotkey as admin so that it can catch keystrokes if REAPER is running privileged as well. @ScottChesworth

**Comment by MatejGolian** [comment]
I agree, I'll do the Kontakt ones.
BTW, other than wat Toni said, there should not be a reason why Kontakt shouldn't work for you. At least none that we're aware of.

**Comment by ScottChesworth** [comment]
I started #4 to troubleshoot.

**Comment by MatejGolian** [comment]
I re-introduced the LIBRARY menu buttons, labelled as 'LIBRARY Browser', since over here at least, clicking 'LIBRARY' does indeed toggle the visibility of the Library Browser - got it confirmed by sighted assistance. The visibility of the browser, or lack there of, does affect OCR results and therefore it's good to have the option to try and disable it, although the script attempts to do it automatically. Note that when you have Kontakt set to Simple view, the Browser always re-opens itself after you close and re-open the reaper FX window.
Furthermore, it seems that hints are being displayed when you hover over those 4 'menu' items. These are the hints for each item:
File: "Load or create an instrument"
Library: "Library: Open the Library Browser to access your libraries, and presets."
View: "View: Switch between Single View and Rack View, Set Zoom, and configure KONTAKT'S layout."
Shop: "Shop: Browse our Shop and discover new products on the Native Instruments website!"

**Pull request merged**
